"""
KORTEX Internal PKI (Phase 5).

Implements the internal Certificate Authority that anchors mutual TLS between
the KORTEX backend's Agent Gateway and the Windows Desktop Agent, per
`docs/architecture/phase5_locked_architecture_spec.md` S11-S14.

Trust model
-----------
There is exactly one trust anchor: the KORTEX Internal Root CA generated by
`initialize_ca()`. It signs exactly two kinds of leaf certificate — the
Gateway's `serverAuth` certificate and each enrolled agent's `clientAuth`
certificate. No external or public CA participates in agent authentication,
and no certificate is ever trusted because it merely parses.

Key custody
-----------
Both backend private keys (the CA's and the Gateway server's) live only in
the `SecretStore`, encrypted at rest under `tenant_id="__system__"`. They are
never written to disk in plaintext, never logged, and never returned to a
client. The one artifact this module does write to disk is the CA's *public*
certificate, which is public by construction and must be distributable to
agent installers.

The agent's own private key is deliberately absent from this module: it is
generated inside Windows CNG on the agent machine, marked non-exportable, and
never transmitted. This module only ever sees that key's CSR.

Revocation
----------
Phase 5 implements no CRL and no OCSP. Revocation is enforced at the
authorization layer instead — the Gateway resolves every certificate's subject
to a live `PrincipalRecord` on connect and re-checks it every 5 seconds, so a
disabled or deleted principal loses its session within that window even though
its certificate remains cryptographically valid until expiry.
"""

from __future__ import annotations

import datetime
import ipaddress
from dataclasses import dataclass
from pathlib import Path
from typing import Final

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import ExtendedKeyUsageOID, NameOID

from kortex.engines.security.exceptions import (
    CaAlreadyExistsError,
    CaUnavailableError,
    CsrValidationError,
    SecretNotFoundError,
    ServerCertificateUnavailableError,
)
from kortex.engines.security.interfaces import ISecretStore

# -- System namespace and handles (spec S22) ---------------------------------

SYSTEM_TENANT_ID: Final[str] = "__system__"

CA_PRIVATE_KEY_HANDLE: Final[str] = "system/pki/ca_private_key"
CA_PUBLIC_CERTIFICATE_HANDLE: Final[str] = "system/pki/ca_public_certificate"
GATEWAY_SERVER_PRIVATE_KEY_HANDLE: Final[str] = "system/pki/gateway_server_private_key"
GATEWAY_SERVER_CERTIFICATE_HANDLE: Final[str] = "system/pki/gateway_server_certificate"

# -- Certificate profile constants (spec S11-S14) ----------------------------

CA_KEY_SIZE_BITS: Final[int] = 4096
LEAF_KEY_SIZE_BITS: Final[int] = 2048
CA_VALIDITY_DAYS: Final[int] = 3650
LEAF_VALIDITY_DAYS: Final[int] = 365

CA_COMMON_NAME: Final[str] = "KORTEX Internal Root CA"
CA_ORGANIZATION: Final[str] = "KORTEX"
CA_ORGANIZATIONAL_UNIT: Final[str] = "Security Engine"

# The CA's public certificate is additionally written here so an installer can
# package it. Public material only — no private key is ever written to disk.
DEFAULT_CA_CERTIFICATE_PATH: Final[Path] = Path("backend/data/pki/kortex_root_ca.crt")


def _utcnow() -> datetime.datetime:
    return datetime.datetime.now(datetime.UTC)


def _ca_subject() -> x509.Name:
    return x509.Name(
        [
            x509.NameAttribute(NameOID.COMMON_NAME, CA_COMMON_NAME),
            x509.NameAttribute(NameOID.ORGANIZATION_NAME, CA_ORGANIZATION),
            x509.NameAttribute(NameOID.ORGANIZATIONAL_UNIT_NAME, CA_ORGANIZATIONAL_UNIT),
        ]
    )


def _private_key_to_pem(key: rsa.RSAPrivateKey) -> str:
    """Serialize a private key to unencrypted PKCS#8 PEM.

    "Unencrypted" here refers only to this in-memory PEM encoding. The value
    is handed directly to `SecretStore.put_secret`, which performs the actual
    AES-256-GCM encryption at rest; it is never written to disk or logged in
    this form.
    """
    return key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode("ascii")


def _certificate_to_pem(certificate: x509.Certificate) -> str:
    return certificate.public_bytes(serialization.Encoding.PEM).decode("ascii")


def certificate_fingerprint(certificate: x509.Certificate) -> str:
    """Return the SHA-256 fingerprint of a certificate's DER encoding."""
    return certificate.fingerprint(hashes.SHA256()).hex()


@dataclass(frozen=True)
class CaMaterial:
    """The Root CA's signing key and certificate, loaded together.

    Held only for the duration of a signing operation. It is never cached on
    the `KortexPki` instance, so a CA revoked or replaced at the SecretStore
    layer stops being usable on the next call rather than at process restart.
    """

    private_key: rsa.RSAPrivateKey
    certificate: x509.Certificate


class KortexPki:
    """Internal Certificate Authority backed by the existing `SecretStore`.

    This class owns no key material of its own: every private key is fetched
    from the `SecretStore` at the moment it is needed and discarded when the
    call returns. Nothing is cached, so revoking access at the SecretStore
    layer takes effect immediately rather than at the next process restart.
    """

    def __init__(self, secret_store: ISecretStore) -> None:
        self._secret_store = secret_store

    # -- CA lifecycle --------------------------------------------------------

    async def ca_exists(self) -> bool:
        """Return whether a Root CA private key is already present.

        A storage-layer failure is never reported as "absent": only an
        explicit not-found result counts, so a transient `SecretStore` outage
        can never be mistaken for "no CA yet" and trigger a regeneration that
        would invalidate every certificate already issued.
        """
        try:
            await self._secret_store.get_secret(CA_PRIVATE_KEY_HANDLE, SYSTEM_TENANT_ID)
        except SecretNotFoundError:
            return False
        return True

    async def initialize_ca(self, certificate_path: Path | None = None) -> x509.Certificate:
        """Generate and persist the KORTEX Internal Root CA.

        Aborts with `CaAlreadyExistsError` if a CA private key already exists.
        This is the single most destructive operation in the PKI — silently
        replacing the CA would orphan every issued client certificate at once
        — so it is never implicit, never idempotent-by-overwrite, and never
        triggered by the Gateway's own boot path.

        Raises:
            CaAlreadyExistsError: If CA material already exists.
        """
        if await self.ca_exists():
            raise CaAlreadyExistsError(
                "A KORTEX Root CA already exists in the SecretStore. "
                "Refusing to overwrite it: doing so would invalidate every client "
                "certificate already issued. Rotate the CA through the documented "
                "offline administrative procedure instead."
            )

        private_key = rsa.generate_private_key(public_exponent=65537, key_size=CA_KEY_SIZE_BITS)
        subject = _ca_subject()
        now = _utcnow()

        certificate = (
            x509.CertificateBuilder()
            .subject_name(subject)
            .issuer_name(subject)
            .public_key(private_key.public_key())
            .serial_number(x509.random_serial_number())
            .not_valid_before(now)
            .not_valid_after(now + datetime.timedelta(days=CA_VALIDITY_DAYS))
            .add_extension(x509.BasicConstraints(ca=True, path_length=None), critical=True)
            .add_extension(
                x509.KeyUsage(
                    digital_signature=False,
                    content_commitment=False,
                    key_encipherment=False,
                    data_encipherment=False,
                    key_agreement=False,
                    key_cert_sign=True,
                    crl_sign=True,
                    encipher_only=False,
                    decipher_only=False,
                ),
                critical=True,
            )
            .add_extension(
                x509.SubjectKeyIdentifier.from_public_key(private_key.public_key()),
                critical=False,
            )
            .sign(private_key, hashes.SHA256())
        )

        await self._secret_store.put_secret(CA_PRIVATE_KEY_HANDLE, SYSTEM_TENANT_ID, _private_key_to_pem(private_key))
        await self._secret_store.put_secret(
            CA_PUBLIC_CERTIFICATE_HANDLE, SYSTEM_TENANT_ID, _certificate_to_pem(certificate)
        )

        target = certificate_path if certificate_path is not None else DEFAULT_CA_CERTIFICATE_PATH
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_certificate_to_pem(certificate), encoding="ascii")

        return certificate

    async def load_ca_private_key(self) -> rsa.RSAPrivateKey:
        """Load the Root CA private key, failing closed if it is unusable.

        Raises:
            CaUnavailableError: If the key is missing, undecryptable, or does
                not parse as an RSA private key.
        """
        try:
            pem = await self._secret_store.get_secret(CA_PRIVATE_KEY_HANDLE, SYSTEM_TENANT_ID)
        except Exception as exc:
            raise CaUnavailableError("The KORTEX Root CA private key could not be read from the SecretStore.") from exc

        try:
            key = serialization.load_pem_private_key(pem.encode("ascii"), password=None)
        except Exception as exc:
            raise CaUnavailableError("The KORTEX Root CA private key is corrupt or unparseable.") from exc

        if not isinstance(key, rsa.RSAPrivateKey):
            raise CaUnavailableError("The stored KORTEX Root CA private key is not an RSA private key.")
        return key

    async def load_ca_certificate(self) -> x509.Certificate:
        """Load the Root CA public certificate, failing closed if unusable.

        Raises:
            CaUnavailableError: If the certificate is missing or unparseable.
        """
        try:
            pem = await self._secret_store.get_secret(CA_PUBLIC_CERTIFICATE_HANDLE, SYSTEM_TENANT_ID)
        except Exception as exc:
            raise CaUnavailableError("The KORTEX Root CA certificate could not be read from the SecretStore.") from exc

        try:
            return x509.load_pem_x509_certificate(pem.encode("ascii"))
        except Exception as exc:
            raise CaUnavailableError("The KORTEX Root CA certificate is corrupt or unparseable.") from exc

    # -- Leaf issuance -------------------------------------------------------

    async def issue_server_certificate(
        self, hostname: str, ip_address: str | None = None
    ) -> tuple[x509.Certificate, str]:
        """Issue the Gateway's `serverAuth` certificate and persist both halves.

        The hostname is placed in both the Subject CN and the SAN. Modern TLS
        clients ignore the CN entirely and match only the SAN, so the SAN entry
        — not the CN — is what actually makes the agent's hostname verification
        succeed.

        Returns:
            The issued certificate and its PEM encoding.
        """
        ca_key = await self.load_ca_private_key()
        ca_certificate = await self.load_ca_certificate()

        server_key = rsa.generate_private_key(public_exponent=65537, key_size=LEAF_KEY_SIZE_BITS)
        now = _utcnow()

        san_entries: list[x509.GeneralName] = [x509.DNSName(hostname)]
        if ip_address:
            san_entries.append(x509.IPAddress(ipaddress.ip_address(ip_address)))

        certificate = (
            x509.CertificateBuilder()
            .subject_name(x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, hostname)]))
            .issuer_name(ca_certificate.subject)
            .public_key(server_key.public_key())
            .serial_number(x509.random_serial_number())
            .not_valid_before(now)
            .not_valid_after(now + datetime.timedelta(days=LEAF_VALIDITY_DAYS))
            .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
            .add_extension(
                x509.KeyUsage(
                    digital_signature=True,
                    content_commitment=False,
                    key_encipherment=True,
                    data_encipherment=False,
                    key_agreement=False,
                    key_cert_sign=False,
                    crl_sign=False,
                    encipher_only=False,
                    decipher_only=False,
                ),
                critical=True,
            )
            .add_extension(x509.ExtendedKeyUsage([ExtendedKeyUsageOID.SERVER_AUTH]), critical=True)
            .add_extension(x509.SubjectAlternativeName(san_entries), critical=False)
            .sign(ca_key, hashes.SHA256())
        )

        certificate_pem = _certificate_to_pem(certificate)
        await self._secret_store.put_secret(
            GATEWAY_SERVER_PRIVATE_KEY_HANDLE, SYSTEM_TENANT_ID, _private_key_to_pem(server_key)
        )
        await self._secret_store.put_secret(GATEWAY_SERVER_CERTIFICATE_HANDLE, SYSTEM_TENANT_ID, certificate_pem)
        return certificate, certificate_pem

    async def load_server_material(self) -> tuple[bytes, bytes]:
        """Load the Gateway server certificate and private key as PEM bytes.

        Raises:
            ServerCertificateUnavailableError: If either half is missing or
                does not parse. The Gateway aborts boot on this — it never
                degrades to plaintext or a self-signed substitute.
        """
        try:
            certificate_pem = await self._secret_store.get_secret(GATEWAY_SERVER_CERTIFICATE_HANDLE, SYSTEM_TENANT_ID)
            key_pem = await self._secret_store.get_secret(GATEWAY_SERVER_PRIVATE_KEY_HANDLE, SYSTEM_TENANT_ID)
        except Exception as exc:
            raise ServerCertificateUnavailableError(
                "The KORTEX Gateway server certificate or private key could not be read from the SecretStore."
            ) from exc

        try:
            x509.load_pem_x509_certificate(certificate_pem.encode("ascii"))
            serialization.load_pem_private_key(key_pem.encode("ascii"), password=None)
        except Exception as exc:
            raise ServerCertificateUnavailableError(
                "The KORTEX Gateway server certificate or private key is corrupt or unparseable."
            ) from exc

        return certificate_pem.encode("ascii"), key_pem.encode("ascii")

    async def load_ca_material(self) -> CaMaterial:
        """Load the CA key and certificate together, failing closed if unusable.

        Callers that sign inside a database transaction must call this
        *before* opening that transaction: reading from the `SecretStore`
        itself opens a transaction, and on SQLite the engine serializes
        session acquisition behind a single non-reentrant write lock, so a
        SecretStore read nested inside another transaction deadlocks.

        Raises:
            CaUnavailableError: If either half is missing or unusable.
        """
        return CaMaterial(
            private_key=await self.load_ca_private_key(),
            certificate=await self.load_ca_certificate(),
        )

    def sign_client_csr_with_material(
        self, material: CaMaterial, csr_bytes: bytes, principal_id: str
    ) -> tuple[x509.Certificate, bytes]:
        """Sign an agent's CSR using already-loaded CA material.

        Synchronous and self-contained: it performs no I/O, so it is safe to
        call from inside an open database transaction.

        The CSR contributes exactly one thing: its public key. Every other
        field of the resulting certificate — subject, validity, key usage,
        extended key usage, basic constraints — is imposed here from the
        backend's own authoritative state. A CSR therefore cannot request a CA
        certificate, a `serverAuth` EKU, a longer lifetime, or a subject
        naming a principal other than the one the enrollment transaction
        actually created.

        Args:
            material: CA key and certificate loaded via `load_ca_material`.
            csr_bytes: The PEM- or DER-encoded CSR submitted by the agent.
            principal_id: The backend-generated principal id to bind as CN.

        Returns:
            The issued certificate and its PEM encoding.

        Raises:
            CsrValidationError: If the CSR is malformed or its embedded
                self-signature does not verify.
        """
        try:
            csr = x509.load_pem_x509_csr(csr_bytes) if b"-----BEGIN" in csr_bytes else x509.load_der_x509_csr(csr_bytes)
        except Exception as exc:
            raise CsrValidationError("The submitted CSR is malformed and could not be parsed.") from exc

        # Proves the submitter holds the private key matching the CSR's public
        # key. Without this a caller could enroll someone else's public key and
        # obtain a certificate they cannot use but the real key holder's agent
        # would collide with.
        if not csr.is_signature_valid:
            raise CsrValidationError("The submitted CSR's self-signature is invalid.")

        now = _utcnow()
        certificate = (
            x509.CertificateBuilder()
            .subject_name(x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, principal_id)]))
            .issuer_name(material.certificate.subject)
            .public_key(csr.public_key())
            .serial_number(x509.random_serial_number())
            .not_valid_before(now)
            .not_valid_after(now + datetime.timedelta(days=LEAF_VALIDITY_DAYS))
            .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
            .add_extension(
                x509.KeyUsage(
                    digital_signature=True,
                    content_commitment=False,
                    key_encipherment=True,
                    data_encipherment=False,
                    key_agreement=False,
                    key_cert_sign=False,
                    crl_sign=False,
                    encipher_only=False,
                    decipher_only=False,
                ),
                critical=True,
            )
            .add_extension(x509.ExtendedKeyUsage([ExtendedKeyUsageOID.CLIENT_AUTH]), critical=True)
            .sign(material.private_key, hashes.SHA256())
        )
        return certificate, _certificate_to_pem(certificate).encode("ascii")

    async def sign_client_csr(self, csr_bytes: bytes, principal_id: str) -> tuple[x509.Certificate, bytes]:
        """Load CA material and sign an agent's CSR into a `clientAuth` certificate.

        The CSR contributes exactly one thing: its public key. Every other
        field of the resulting certificate — subject, validity, key usage,
        extended key usage, basic constraints — is imposed here from the
        backend's own authoritative state. A CSR therefore cannot request a CA
        certificate, a `serverAuth` EKU, a longer lifetime, or a subject
        naming a principal other than the one the enrollment transaction
        actually created.

        Convenience wrapper for callers that are not inside a transaction.
        Code that signs within one must use `load_ca_material` followed by
        `sign_client_csr_with_material` — see `load_ca_material`.

        Args:
            csr_bytes: The PEM- or DER-encoded CSR submitted by the agent.
            principal_id: The backend-generated principal id to bind as CN.

        Returns:
            The issued certificate and its PEM encoding.

        Raises:
            CaUnavailableError: If CA material is missing or unusable.
            CsrValidationError: If the CSR is malformed or its embedded
                self-signature does not verify.
        """
        material = await self.load_ca_material()
        return self.sign_client_csr_with_material(material, csr_bytes, principal_id)
