"""KORTEX Backup Engine — Automated backup scheduling, packaging, and management."""

from __future__ import annotations

from kortex.engines.backup.constants import (
    BACKUP_ENGINE_NAME,
    BACKUP_EXTENSION,
    BACKUP_SECURITY_CLASSIFICATION,
    CAPABILITY_BACKUP_CREATE,
    CAPABILITY_BACKUP_DELETE,
    CAPABILITY_BACKUP_DIAGNOSTICS_GET,
    CAPABILITY_BACKUP_GET,
    CAPABILITY_BACKUP_LIST,
    CAPABILITY_BACKUP_VERIFY,
    CURRENT_BACKUP_FORMAT_VERSION,
    CURRENT_ENGINE_VERSION,
    PERMISSION_BACKUP_MANAGE,
    PERMISSION_BACKUP_READ,
    BackupComponentType,
    BackupScope,
    BackupState,
    RetentionPolicyType,
)
from kortex.engines.backup.crypto import BackupCryptoManager
from kortex.engines.backup.engine import BackupEngine
from kortex.engines.backup.exceptions import (
    BackupConcurrencyError,
    BackupCorruptionError,
    BackupEncryptionError,
    BackupError,
    BackupNotFoundError,
    BackupPathSecurityError,
    BackupRetentionError,
    BackupScopeError,
    BackupStorageError,
    BackupValidationError,
)
from kortex.engines.backup.models import (
    BackupConfig,
    BackupDiagnostics,
    BackupManifest,
    BackupMetadata,
    ChecksumManifest,
    ChecksumManifestEntry,
    CompressionMetadata,
    CreateBackupRequest,
    CreateBackupResponse,
    DeleteBackupRequest,
    DeleteBackupResponse,
    EncryptionMetadata,
    GetBackupRequest,
    GetBackupResponse,
    ListBackupsRequest,
    ListBackupsResponse,
    ManifestComponentEntry,
    RetentionPolicy,
    VerifyBackupRequest,
    VerifyBackupResponse,
)
from kortex.engines.backup.repository import BackupRepository
from kortex.engines.backup.retention import RetentionEngine
from kortex.engines.backup.verifier import BackupVerifier

__all__ = [
    "BACKUP_ENGINE_NAME",
    "BACKUP_EXTENSION",
    "BACKUP_SECURITY_CLASSIFICATION",
    "CAPABILITY_BACKUP_CREATE",
    "CAPABILITY_BACKUP_DELETE",
    "CAPABILITY_BACKUP_DIAGNOSTICS_GET",
    "CAPABILITY_BACKUP_GET",
    "CAPABILITY_BACKUP_LIST",
    "CAPABILITY_BACKUP_VERIFY",
    "CURRENT_BACKUP_FORMAT_VERSION",
    "CURRENT_ENGINE_VERSION",
    "PERMISSION_BACKUP_MANAGE",
    "PERMISSION_BACKUP_READ",
    "BackupComponentType",
    "BackupConcurrencyError",
    "BackupConfig",
    "BackupCorruptionError",
    "BackupCryptoManager",
    "BackupDiagnostics",
    "BackupEncryptionError",
    "BackupEngine",
    "BackupError",
    "BackupManifest",
    "BackupMetadata",
    "BackupNotFoundError",
    "BackupPathSecurityError",
    "BackupRepository",
    "BackupRetentionError",
    "BackupScope",
    "BackupScopeError",
    "BackupState",
    "BackupStorageError",
    "BackupValidationError",
    "BackupVerifier",
    "ChecksumManifest",
    "ChecksumManifestEntry",
    "CompressionMetadata",
    "CreateBackupRequest",
    "CreateBackupResponse",
    "DeleteBackupRequest",
    "DeleteBackupResponse",
    "EncryptionMetadata",
    "GetBackupRequest",
    "GetBackupResponse",
    "ListBackupsRequest",
    "ListBackupsResponse",
    "ManifestComponentEntry",
    "RetentionEngine",
    "RetentionPolicy",
    "RetentionPolicyType",
    "VerifyBackupRequest",
    "VerifyBackupResponse",
]
