# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kortex/engines/agent_gateway/protos/agent.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'kortex/engines/agent_gateway/protos/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/kortex/engines/agent_gateway/protos/agent.proto\x12\x0fkortex.agent.v1\"I\n\x0c\x41gentMessage\x12.\n\x06status\x18\x01 \x01(\x0b\x32\x1c.kortex.agent.v1.AgentStatusH\x00\x42\t\n\x07payload\"O\n\x0eGatewayMessage\x12\x32\n\x0bsession_ack\x18\x01 \x01(\x0b\x32\x1b.kortex.agent.v1.SessionAckH\x00\x42\t\n\x07payload\">\n\x0b\x41gentStatus\x12\x1f\n\x17machine_installation_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\" \n\nSessionAck\x12\x12\n\nsession_id\x18\x01 \x01(\t2d\n\x13\x44\x65sktopAgentGateway\x12M\n\x07\x43onnect\x12\x1d.kortex.agent.v1.AgentMessage\x1a\x1f.kortex.agent.v1.GatewayMessage(\x01\x30\x01\x42\x12\xaa\x02\x0fKortex.Agent.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kortex.engines.agent_gateway.protos.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\017Kortex.Agent.V1'
  _globals['_AGENTMESSAGE']._serialized_start=68
  _globals['_AGENTMESSAGE']._serialized_end=141
  _globals['_GATEWAYMESSAGE']._serialized_start=143
  _globals['_GATEWAYMESSAGE']._serialized_end=222
  _globals['_AGENTSTATUS']._serialized_start=224
  _globals['_AGENTSTATUS']._serialized_end=286
  _globals['_SESSIONACK']._serialized_start=288
  _globals['_SESSIONACK']._serialized_end=320
  _globals['_DESKTOPAGENTGATEWAY']._serialized_start=322
  _globals['_DESKTOPAGENTGATEWAY']._serialized_end=422
# @@protoc_insertion_point(module_scope)
