"""
KORTEX Recipe Engine Abstract Interfaces and Protocols.

Defines all formal interface contracts for parsing, compilation, validation,
registration, loading, packaging, installation, permission checking, versioning,
and engine diagnostics.
"""

from __future__ import annotations

from typing import Any, Protocol

from kortex.engines.recipe.models import (
    RecipeCompilationResult,
    RecipeDefinition,
    RecipeInstallationResult,
    RecipeManifest,
    RecipePackage,
    RecipeRemovalResult,
    RecipeUpgradeResult,
    RecipeValidationResult,
)
from kortex.engines.workflow.models import WorkflowDefinition


class IEngineDiagnostics(Protocol):
    """Standardized Diagnostics Interface exposed by all KORTEX System Engines."""

    def health(self) -> dict[str, Any]: ...
    def metrics(self) -> dict[str, Any]: ...
    def diagnostics(self) -> dict[str, Any]: ...
    def status(self) -> str: ...
    def version(self) -> str: ...
    def capabilities(self) -> list[str]: ...


class IRecipeParser(Protocol):
    """Interface for loading and parsing raw YAML/JSON recipe specifications."""

    def parse_recipe_yaml(self, raw_content: str) -> dict[str, Any]: ...
    def parse_manifest_yaml(self, raw_content: str) -> RecipeManifest: ...
    def parse_definition(self, raw_recipe: str, raw_manifest: str | None = None) -> RecipeDefinition: ...


class IRecipeCompiler(Protocol):
    """Pure deterministic compiler translating Recipe Definitions into Workflow Definitions."""

    def compile(
        self, recipe: RecipeDefinition, input_parameters: dict[str, Any] | None = None
    ) -> RecipeCompilationResult: ...


class IRecipeValidator(Protocol):
    """Interface for verifying recipe schema, security rules, DSL, and signatures."""

    def validate_schema(self, recipe: RecipeDefinition) -> RecipeValidationResult: ...
    def validate_security(self, raw_files: dict[str, bytes]) -> RecipeValidationResult: ...
    def validate_recipe(
        self, recipe: RecipeDefinition, raw_files: dict[str, bytes] | None = None
    ) -> RecipeValidationResult: ...


class IRecipeRegistry(Protocol):
    """Interface for recipe cataloging, searching, and lookup in Kernel Registry."""

    def register(self, recipe: RecipeDefinition) -> bool: ...
    def unregister(self, recipe_id: str, version: str) -> bool: ...
    def find_by_id(self, recipe_id: str, version: str | None = None) -> RecipeDefinition | None: ...
    def find_by_namespace(self, namespace: str) -> list[RecipeDefinition]: ...
    def search(self, query: str) -> list[RecipeDefinition]: ...
    def list_all(self) -> list[RecipeDefinition]: ...


class IRecipeLoader(Protocol):
    """Interface for loading recipe assets from directories, ZIPs, or .kortex-recipe files."""

    def load_from_folder(self, folder_path: str) -> RecipeDefinition: ...
    def load_from_package(self, package_bytes: bytes) -> RecipeDefinition: ...
    def read_package_files(self, package_bytes: bytes) -> dict[str, bytes]: ...


class IRecipeInstaller(Protocol):
    """Lifecycle manager for recipe installation, upgrading, removal, and rollback."""

    async def install(
        self, recipe: RecipeDefinition, package_bytes: bytes | None = None
    ) -> RecipeInstallationResult: ...
    async def upgrade(self, recipe: RecipeDefinition, package_bytes: bytes | None = None) -> RecipeUpgradeResult: ...
    async def remove(self, recipe_id: str, version: str) -> RecipeRemovalResult: ...
    async def rollback(self, recipe_id: str, target_version: str) -> RecipeInstallationResult: ...


class IRecipePackager(Protocol):
    """Interface for creating standalone .kortex-recipe archive packages."""

    def create_package(self, recipe_folder_files: dict[str, bytes], manifest: RecipeManifest) -> RecipePackage: ...
    def verify_checksum(self, package: RecipePackage) -> bool: ...


class IVersionResolver(Protocol):
    """SemVer parsing, comparison, and dependency resolution provider."""

    def is_compatible(self, required_version: str, available_version: str) -> bool: ...
    def compare(self, version1: str, version2: str) -> int: ...
    def resolve_dependencies(self, dependencies: dict[str, str], available: dict[str, str]) -> bool: ...


class IPermissionValidator(Protocol):
    """Interface for validating requested capability access and permissions."""

    def validate_permissions(self, required_capabilities: list[str], granted_capabilities: list[str]) -> bool: ...


class ICompatibilityValidator(Protocol):
    """Interface for verifying engine and system version compatibility."""

    def validate_compatibility(self, recipe: RecipeDefinition, system_versions: dict[str, str]) -> bool: ...


class IRecipeEngine(IEngineDiagnostics, Protocol):
    """Central orchestration contract for the KORTEX Recipe Engine."""

    def parse(self, raw_recipe: str, raw_manifest: str | None = None) -> RecipeDefinition: ...
    def validate(self, recipe: RecipeDefinition) -> RecipeValidationResult: ...
    def compile(
        self, recipe: RecipeDefinition, input_parameters: dict[str, Any] | None = None
    ) -> WorkflowDefinition: ...
    async def install(self, package_bytes: bytes) -> RecipeInstallationResult: ...
    async def upgrade(self, package_bytes: bytes) -> RecipeUpgradeResult: ...
    async def remove(self, recipe_id: str, version: str) -> RecipeRemovalResult: ...
    def package(self, files: dict[str, bytes], manifest: RecipeManifest) -> RecipePackage: ...
