"""KORTEX Update Engine — System updates and version management.

Phase 7 — Production Hardening — Update Engine.
Authoritative infrastructure engine for update discovery, verification,
staging, migration, filesystem swapping, and disaster recovery coordination.
"""

from __future__ import annotations

from kortex.engines.update.constants import (
    ALL_UPDATE_EVENTS,
    CAPABILITY_UPDATE_APPLY,
    CAPABILITY_UPDATE_CANCEL,
    CAPABILITY_UPDATE_CHECK,
    CAPABILITY_UPDATE_DIAGNOSTICS_GET,
    CAPABILITY_UPDATE_GET,
    CAPABILITY_UPDATE_STAGE,
    CURRENT_ENGINE_VERSION,
    EVENT_UPDATE_APPLIED,
    EVENT_UPDATE_CHECKED,
    EVENT_UPDATE_COMPLETED,
    EVENT_UPDATE_FAILED,
    EVENT_UPDATE_MANIFEST_VERIFIED,
    EVENT_UPDATE_MIGRATED,
    EVENT_UPDATE_OPERATOR_INTERVENTION_REQUIRED,
    EVENT_UPDATE_QUIESCED,
    EVENT_UPDATE_ROLLED_BACK,
    EVENT_UPDATE_SAFETY_CHECKPOINT_CREATED,
    EVENT_UPDATE_STAGED,
    EVENT_UPDATE_VERIFIED,
    PERMISSION_UPDATE_MANAGE,
    PERMISSION_UPDATE_READ,
    UPDATE_ENGINE_NAME,
    UpdateJournalPhase,
    UpdateState,
)
from kortex.engines.update.engine import UpdateEngine
from kortex.engines.update.exceptions import (
    UpdateArchiveSecurityError,
    UpdateAuthenticationError,
    UpdateAuthorizationError,
    UpdateCheckpointError,
    UpdateChecksumMismatchError,
    UpdateCompatibilityError,
    UpdateConcurrencyError,
    UpdateDiskSpaceError,
    UpdateDowngradeError,
    UpdateError,
    UpdateKeyNotFoundError,
    UpdateManifestError,
    UpdateMigrationError,
    UpdateNotFoundError,
    UpdateOperatorActionRequiredError,
    UpdatePathTraversalError,
    UpdatePlatformMismatchError,
    UpdateQuiescenceError,
    UpdateRollbackError,
    UpdateSchemaIncompatibleError,
    UpdateSecurityError,
    UpdateSignatureError,
    UpdateSwapError,
    UpdateVerificationError,
    UpdateZipBombError,
)
from kortex.engines.update.interfaces import IUpdateEngine
from kortex.engines.update.models import (
    UpdateApplyRequest,
    UpdateApplyResponse,
    UpdateCancelRequest,
    UpdateCancelResponse,
    UpdateCheckRequest,
    UpdateCheckResponse,
    UpdateConfig,
    UpdateGetRequest,
    UpdateGetResponse,
    UpdateHistoryEntry,
    UpdateJournalRecord,
    UpdateManifest,
    UpdateStageRequest,
    UpdateStageResponse,
)

__all__ = [
    # Events
    "ALL_UPDATE_EVENTS",
    "CAPABILITY_UPDATE_APPLY",
    "CAPABILITY_UPDATE_CANCEL",
    # Capabilities & Permissions
    "CAPABILITY_UPDATE_CHECK",
    "CAPABILITY_UPDATE_DIAGNOSTICS_GET",
    "CAPABILITY_UPDATE_GET",
    "CAPABILITY_UPDATE_STAGE",
    "CURRENT_ENGINE_VERSION",
    "EVENT_UPDATE_APPLIED",
    "EVENT_UPDATE_CHECKED",
    "EVENT_UPDATE_COMPLETED",
    "EVENT_UPDATE_FAILED",
    "EVENT_UPDATE_MANIFEST_VERIFIED",
    "EVENT_UPDATE_MIGRATED",
    "EVENT_UPDATE_OPERATOR_INTERVENTION_REQUIRED",
    "EVENT_UPDATE_QUIESCED",
    "EVENT_UPDATE_ROLLED_BACK",
    "EVENT_UPDATE_SAFETY_CHECKPOINT_CREATED",
    "EVENT_UPDATE_STAGED",
    "EVENT_UPDATE_VERIFIED",
    "PERMISSION_UPDATE_MANAGE",
    "PERMISSION_UPDATE_READ",
    "UPDATE_ENGINE_NAME",
    "IUpdateEngine",
    "UpdateApplyRequest",
    "UpdateApplyResponse",
    "UpdateArchiveSecurityError",
    "UpdateAuthenticationError",
    "UpdateAuthorizationError",
    "UpdateCancelRequest",
    "UpdateCancelResponse",
    "UpdateCheckRequest",
    "UpdateCheckResponse",
    "UpdateCheckpointError",
    "UpdateChecksumMismatchError",
    "UpdateCompatibilityError",
    "UpdateConcurrencyError",
    "UpdateConfig",
    "UpdateDiskSpaceError",
    "UpdateDowngradeError",
    # Engine & Core
    "UpdateEngine",
    # Exceptions
    "UpdateError",
    "UpdateGetRequest",
    "UpdateGetResponse",
    "UpdateHistoryEntry",
    "UpdateJournalPhase",
    "UpdateJournalRecord",
    "UpdateKeyNotFoundError",
    # Models
    "UpdateManifest",
    "UpdateManifestError",
    "UpdateMigrationError",
    "UpdateNotFoundError",
    "UpdateOperatorActionRequiredError",
    "UpdatePathTraversalError",
    "UpdatePlatformMismatchError",
    "UpdateQuiescenceError",
    "UpdateRollbackError",
    "UpdateSchemaIncompatibleError",
    "UpdateSecurityError",
    "UpdateSignatureError",
    "UpdateStageRequest",
    "UpdateStageResponse",
    # States & Phases
    "UpdateState",
    "UpdateSwapError",
    "UpdateVerificationError",
    "UpdateZipBombError",
]
