"""KORTEX OS Document Engine package.

This package provides the foundational data models, enums, interfaces, exceptions,
and abstract base classes for the Document Engine (Milestone 1).
"""

from __future__ import annotations

from kortex.engines.document.adapters.dummy_adapter import DummyDocumentAdapter
from kortex.engines.document.base_adapter import BaseDocumentAdapter
from kortex.engines.document.engine import DocumentEngine
from kortex.engines.document.loader import DocumentAdapterLoader
from kortex.engines.document.intelligence import (
    DefaultDocumentIntelligenceProvider,
    DefaultDocumentRecommendationProvider,
    DocumentIntelligenceModel,
)
from kortex.engines.document.recovery import (
    CheckpointState,
    DocumentRecoveryManager,
    FailureMetadata,
)
from kortex.engines.document.security import (
    DefaultVerificationService,
    DocumentSecurityVerifier,
    DocumentStorageBinder,
    IVerificationService,
)
from kortex.engines.document.diagnostics import DocumentDiagnostics
from kortex.engines.document.events import (
    DocumentAdapterRegisteredEvent,
    DocumentArchivedEvent,
    DocumentBaseEvent,
    DocumentCreatedEvent,
    DocumentIntelligenceUpdatedEvent,
    DocumentLifecycleTransitionedEvent,
    DocumentOperationCompletedEvent,
    DocumentOperationFailedEvent,
    DocumentOperationStartedEvent,
    DocumentPublishedEvent,
    DocumentSupersededEvent,
)
from kortex.engines.document.exceptions import (
    AdapterExecutionError,
    AdapterNotFoundError,
    DocumentAdapterError,
    DocumentEngineError,
    DocumentLifecycleError,
    DocumentOperationError,
    DocumentProfileNotFoundError,
    DocumentRecoveryError,
    DocumentSecurityError,
    DocumentTemplateError,
)
from kortex.engines.document.interfaces import (
    IAdapterPipelineExecutor,
    IAdapterSandbox,
    IDocumentAdapterRegistry,
    IDocumentEngine,
    IDocumentIntelligenceProvider,
    IDocumentLifecycleManager,
    IDocumentOperationProfileManager,
    IDocumentRecommendationProvider,
    IDocumentRecoveryProvider,
    ITemplateBinder,
    ITemplateLibrary,
)
from kortex.engines.document.models import (
    AdapterCapability,
    AdapterMetadata,
    AdapterPipelineDefinition,
    AdapterSandboxConfig,
    BindingContext,
    DocumentLifecycleState,
    DocumentMetadata,
    DocumentOperationProfile,
    DocumentOperationType,
    DocumentVersion,
    OperationRequest,
    OperationResult,
    PipelineExecutionMode,
    PipelineStage,
    PreviewOptions,
    PreviewResult,
    SecurityClassification,
    SecurityMetadata,
    TemplateSchema,
    ValidationReport,
)

__all__ = [
    "AdapterCapability",
    "AdapterExecutionError",
    "AdapterMetadata",
    "AdapterNotFoundError",
    "AdapterPipelineDefinition",
    "AdapterSandboxConfig",
    "BaseDocumentAdapter",
    "BindingContext",
    "CheckpointState",
    "DefaultDocumentIntelligenceProvider",
    "DefaultDocumentRecommendationProvider",
    "DefaultVerificationService",
    "DocumentAdapterError",
    "DocumentAdapterLoader",
    "DocumentAdapterRegisteredEvent",
    "DocumentArchivedEvent",
    "DocumentBaseEvent",
    "DocumentCreatedEvent",
    "DocumentDiagnostics",
    "DocumentEngine",
    "DocumentEngineError",
    "DocumentIntelligenceModel",
    "DocumentIntelligenceUpdatedEvent",
    "DocumentLifecycleError",
    "DocumentLifecycleState",
    "DocumentLifecycleTransitionedEvent",
    "DocumentMetadata",
    "DocumentOperationCompletedEvent",
    "DocumentOperationError",
    "DocumentOperationFailedEvent",
    "DocumentOperationProfile",
    "DocumentOperationStartedEvent",
    "DocumentOperationType",
    "DocumentProfileNotFoundError",
    "DocumentPublishedEvent",
    "DocumentRecoveryError",
    "DocumentRecoveryManager",
    "DocumentSecurityError",
    "DocumentSecurityVerifier",
    "DocumentStorageBinder",
    "DocumentSupersededEvent",
    "DocumentTemplateError",
    "DocumentVersion",
    "DummyDocumentAdapter",
    "FailureMetadata",
    "IAdapterPipelineExecutor",
    "IAdapterSandbox",
    "IDocumentAdapterRegistry",
    "IDocumentEngine",
    "IDocumentIntelligenceProvider",
    "IDocumentLifecycleManager",
    "IDocumentOperationProfileManager",
    "IDocumentRecommendationProvider",
    "IDocumentRecoveryProvider",
    "ITemplateBinder",
    "ITemplateLibrary",
    "IVerificationService",
    "OperationRequest",
    "OperationResult",
    "PipelineExecutionMode",
    "PipelineStage",
    "PreviewOptions",
    "PreviewResult",
    "SecurityClassification",
    "SecurityMetadata",
    "TemplateSchema",
    "ValidationReport",
]
