"""baseline schema

Represents the CURRENT schema exactly as `kortex.core.db.Base.metadata.
create_all()` already produces it in production (generated mechanically
via `alembic revision --autogenerate` against an empty database, not
hand-transcribed, so it is byte-for-byte faithful to the 30 tables
`Base.metadata` currently registers). This is a baseline, not a schema
cleanup -- no refactoring, normalization, renaming, or speculative
index/constraint changes were made to the autogenerated output.

Known baseline-downgrade limitation: `downgrade()` drops every table
this revision creates, in dependency-safe order -- there is no
"previous schema" to restore to below a baseline, so downgrading past
this revision is inherently destructive (all data is lost), not
partially reversible. This is an inherent property of any baseline
revision, not a defect specific to this one.

Revision ID: 81d6d64c51ba
Revises:
Create Date: 2026-09-02 02:40:11.043649

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81d6d64c51ba"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_agent_tasks",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("task_json", sa.Text(), nullable=False),
        sa.Column("steps_json", sa.Text(), nullable=False),
        sa.Column("pending_calls_json", sa.Text(), nullable=False),
        sa.Column("resume_token_json", sa.Text(), nullable=True),
        sa.Column("token_usage_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "task_id", name="uq_ai_agent_task_identity"),
    )
    op.create_index("ix_ai_agent_task_lookup", "ai_agent_tasks", ["tenant_id", "task_id"], unique=False)
    op.create_index("ix_ai_agent_task_tenant_status", "ai_agent_tasks", ["tenant_id", "status"], unique=False)
    op.create_table(
        "ai_conversation_turns",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("user_content", sa.Text(), nullable=False),
        sa.Column("assistant_content", sa.Text(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "conversation_id", "sequence", name="uq_ai_conversation_turn_sequence"),
    )
    op.create_index(
        "ix_ai_conversation_turn_lookup",
        "ai_conversation_turns",
        ["tenant_id", "conversation_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "ai_decision_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("provider_id", sa.String(length=64), nullable=True),
        sa.Column("model_name", sa.String(length=64), nullable=True),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("output_hash", sa.String(length=64), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("tool_calls_json", sa.Text(), nullable=False),
        sa.Column("approval_request_id", sa.String(length=36), nullable=True),
        sa.Column("policy_violations_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ai_decision_tenant_created", "ai_decision_records", ["tenant_id", "created_at"], unique=False)
    op.create_table(
        "ai_governance_policies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("strict_local_only", sa.Boolean(), nullable=False),
        sa.Column("require_human_approval_for_mutations", sa.Boolean(), nullable=False),
        sa.Column("banned_prompt_patterns_json", sa.Text(), nullable=False),
        sa.Column("pii_redaction_enabled", sa.Boolean(), nullable=False),
        sa.Column("allowed_tools_json", sa.Text(), nullable=True),
        sa.Column("blocked_tools_json", sa.Text(), nullable=False),
        sa.Column("max_tokens_per_request", sa.Integer(), nullable=False),
        sa.Column("max_daily_budget_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_governance_policies_tenant_id"), "ai_governance_policies", ["tenant_id"], unique=True)
    op.create_table(
        "ai_tenant_quotas",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("daily_token_limit", sa.Integer(), nullable=False),
        sa.Column("monthly_token_limit", sa.Integer(), nullable=False),
        sa.Column("daily_tokens_consumed", sa.Integer(), nullable=False),
        sa.Column("monthly_tokens_consumed", sa.Integer(), nullable=False),
        sa.Column("last_reset_date", sa.String(length=10), nullable=False),
        sa.Column("max_concurrent_agents", sa.Integer(), nullable=False),
        sa.Column("max_concurrent_generations", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_tenant_quotas_tenant_id"), "ai_tenant_quotas", ["tenant_id"], unique=True)
    op.create_table(
        "approval_delegations",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("delegator_id", sa.String(length=64), nullable=False),
        sa.Column("delegatee_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_approval_delegations_lookup",
        "approval_delegations",
        ["tenant_id", "delegatee_id", "role", "is_active"],
        unique=False,
    )
    op.create_index(op.f("ix_approval_delegations_tenant_id"), "approval_delegations", ["tenant_id"], unique=False)
    op.create_table(
        "approval_requests",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("instance_id", sa.String(length=36), nullable=True),
        sa.Column("step_id", sa.String(length=64), nullable=True),
        sa.Column("required_role", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("timeout_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("context_snapshot_json", sa.Text(), nullable=False),
        sa.Column("signature_required", sa.Boolean(), nullable=False),
        sa.Column("requester_principal_id", sa.String(length=255), nullable=True),
        sa.Column("requester_principal_type", sa.String(length=32), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("action_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approval_requests_correlation_id"), "approval_requests", ["correlation_id"], unique=False)
    op.create_index("ix_approval_requests_instance", "approval_requests", ["instance_id"], unique=False)
    op.create_index(op.f("ix_approval_requests_instance_id"), "approval_requests", ["instance_id"], unique=False)
    op.create_index(
        op.f("ix_approval_requests_requester_principal_id"),
        "approval_requests",
        ["requester_principal_id"],
        unique=False,
    )
    op.create_index(op.f("ix_approval_requests_state"), "approval_requests", ["state"], unique=False)
    op.create_index(op.f("ix_approval_requests_tenant_id"), "approval_requests", ["tenant_id"], unique=False)
    op.create_index("ix_approval_requests_tenant_state", "approval_requests", ["tenant_id", "state"], unique=False)
    op.create_table(
        "connector_action_history",
        sa.Column("profile_id", sa.String(length=64), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("execution_time_ms", sa.Float(), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("driver_id", sa.String(length=255), nullable=True),
        sa.Column("error_details_json", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "connector_profiles",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("driver_id", sa.String(length=255), nullable=False),
        sa.Column("secret_handle", sa.String(length=255), nullable=True),
        sa.Column("rate_limit_per_sec", sa.Float(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("options_json", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_connector_profiles_tenant_id"), "connector_profiles", ["tenant_id"], unique=False)
    op.create_table(
        "document_operation_history",
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("profile_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("version_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("execution_time_ms", sa.Float(), nullable=False),
        sa.Column("output_storage_key", sa.String(length=512), nullable=True),
        sa.Column("validation_report_json", sa.Text(), nullable=True),
        sa.Column("errors_json", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_operation_history_document_id"), "document_operation_history", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_operation_history_profile_id"), "document_operation_history", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_operation_history_request_id"), "document_operation_history", ["request_id"], unique=True
    )
    op.create_index(
        op.f("ix_document_operation_history_tenant_id"), "document_operation_history", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_operation_history_version_id"), "document_operation_history", ["version_id"], unique=False
    )
    op.create_table(
        "document_operation_profiles",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("profile_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("namespace", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("business_operation", sa.String(length=64), nullable=False),
        sa.Column("required_template_id", sa.String(length=128), nullable=True),
        sa.Column("output_bucket", sa.String(length=128), nullable=False),
        sa.Column("pipeline_definition_json", sa.Text(), nullable=True),
        sa.Column("permissions_json", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "profile_id", "version", name="uq_tenant_profile_version"),
    )
    op.create_index(
        op.f("ix_document_operation_profiles_business_operation"),
        "document_operation_profiles",
        ["business_operation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_operation_profiles_namespace"), "document_operation_profiles", ["namespace"], unique=False
    )
    op.create_index(
        op.f("ix_document_operation_profiles_profile_id"), "document_operation_profiles", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_operation_profiles_tenant_id"), "document_operation_profiles", ["tenant_id"], unique=False
    )
    op.create_table(
        "document_template_schemas",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("template_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("namespace", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("placeholders_json", sa.Text(), nullable=True),
        sa.Column("required_fields_json", sa.Text(), nullable=True),
        sa.Column("schema_definition_json", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "template_id", "version", name="uq_tenant_template_version"),
    )
    op.create_index(
        op.f("ix_document_template_schemas_namespace"), "document_template_schemas", ["namespace"], unique=False
    )
    op.create_index(
        op.f("ix_document_template_schemas_template_id"), "document_template_schemas", ["template_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_template_schemas_tenant_id"), "document_template_schemas", ["tenant_id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("document_type", sa.String(length=64), nullable=False),
        sa.Column("current_version_id", sa.String(length=36), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_current_version_id"), "documents", ["current_version_id"], unique=False)
    op.create_index(op.f("ix_documents_tenant_id"), "documents", ["tenant_id"], unique=False)
    op.create_table(
        "event_outbox",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_outbox_status"), "event_outbox", ["status"], unique=False)
    op.create_index(op.f("ix_event_outbox_tenant_id"), "event_outbox", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_event_outbox_topic"), "event_outbox", ["topic"], unique=False)
    op.create_table(
        "external_executions",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("operation_type", sa.String(length=32), nullable=False),
        sa.Column("target", sa.String(length=256), nullable=False),
        sa.Column("parameters_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("output_json", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("execution_time_ms", sa.Float(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("timeout_seconds", sa.Float(), nullable=False),
        sa.Column("retry_policy_json", sa.Text(), nullable=True),
        sa.Column("approval_request_id", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_external_executions_tenant_idempotency"),
    )
    op.create_index(
        op.f("ix_external_executions_idempotency_key"), "external_executions", ["idempotency_key"], unique=False
    )
    op.create_index(op.f("ix_external_executions_status"), "external_executions", ["status"], unique=False)
    op.create_index(op.f("ix_external_executions_tenant_id"), "external_executions", ["tenant_id"], unique=False)
    op.create_index(
        "ix_external_executions_tenant_status", "external_executions", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "finance_invoices",
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("customer_name", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("invoice_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_finance_invoices_tenant_id"), "finance_invoices", ["tenant_id"], unique=False)
    op.create_table(
        "idempotency_records",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("capability_name", sa.String(length=128), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_idempotency_tenant_key"),
    )
    op.create_index(
        op.f("ix_idempotency_records_idempotency_key"), "idempotency_records", ["idempotency_key"], unique=False
    )
    op.create_index(op.f("ix_idempotency_records_state"), "idempotency_records", ["state"], unique=False)
    op.create_index(op.f("ix_idempotency_records_tenant_id"), "idempotency_records", ["tenant_id"], unique=False)
    op.create_table(
        "knowledge_annotations",
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("annotation_id", sa.String(length=255), nullable=False),
        sa.Column("target_record_id", sa.String(length=255), nullable=False),
        sa.Column("annotation_type", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("actor_type", sa.String(length=64), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("annotation_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("supersedes_annotation_id", sa.String(length=255), nullable=True),
        sa.Column("insertion_sequence", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "annotation_id", name="uq_knowledge_annotations_identity"),
    )
    op.create_index(
        op.f("ix_knowledge_annotations_insertion_sequence"),
        "knowledge_annotations",
        ["insertion_sequence"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_annotations_target_record_id"), "knowledge_annotations", ["target_record_id"], unique=False
    )
    op.create_index(op.f("ix_knowledge_annotations_tenant_id"), "knowledge_annotations", ["tenant_id"], unique=False)
    op.create_table(
        "knowledge_packs",
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("asset_id", sa.String(length=255), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("digital_signature", sa.String(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("bucket_name", sa.String(length=255), nullable=False),
        sa.Column("loaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "asset_id", name="uq_knowledge_packs_identity"),
    )
    op.create_index(op.f("ix_knowledge_packs_tenant_id"), "knowledge_packs", ["tenant_id"], unique=False)
    op.create_table(
        "knowledge_records",
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("record_id", sa.String(length=255), nullable=False),
        sa.Column("version_id", sa.String(length=255), nullable=False),
        sa.Column("parent_version_id", sa.String(length=255), nullable=True),
        sa.Column("lineage_path", sa.JSON(), nullable=False),
        sa.Column("record_type", sa.String(length=64), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("trust_state", sa.String(length=64), nullable=False),
        sa.Column("classification", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("created_by_type", sa.String(length=64), nullable=False),
        sa.Column("record_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("successor_version_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "record_id", "version_id", name="uq_knowledge_records_identity"),
    )
    op.create_index(op.f("ix_knowledge_records_record_id"), "knowledge_records", ["record_id"], unique=False)
    op.create_index(op.f("ix_knowledge_records_tenant_id"), "knowledge_records", ["tenant_id"], unique=False)
    op.create_table(
        "security_audit_records",
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(), nullable=False),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("actor_type", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=512), nullable=True),
        sa.Column("previous_state_hash", sa.String(length=64), nullable=True),
        sa.Column("new_state_hash", sa.String(length=64), nullable=True),
        sa.Column("client_ip", sa.String(length=64), nullable=True),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_security_audit_records_action"), "security_audit_records", ["action"], unique=False)
    op.create_index(op.f("ix_security_audit_records_actor_id"), "security_audit_records", ["actor_id"], unique=False)
    op.create_index(op.f("ix_security_audit_records_audit_id"), "security_audit_records", ["audit_id"], unique=True)
    op.create_index(
        op.f("ix_security_audit_records_resource_id"), "security_audit_records", ["resource_id"], unique=False
    )
    op.create_index(op.f("ix_security_audit_records_tenant_id"), "security_audit_records", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_security_audit_records_timestamp_utc"), "security_audit_records", ["timestamp_utc"], unique=False
    )
    op.create_table(
        "security_principals",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("principal_id", sa.String(length=255), nullable=False),
        sa.Column("principal_type", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("credential_hash", sa.String(length=512), nullable=True),
        sa.Column("roles", sa.JSON(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "principal_id", "principal_type", name="uq_security_principals_tenant_principal"
        ),
    )
    op.create_index(op.f("ix_security_principals_principal_id"), "security_principals", ["principal_id"], unique=False)
    op.create_index(op.f("ix_security_principals_tenant_id"), "security_principals", ["tenant_id"], unique=False)
    op.create_table(
        "security_role_permissions",
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("permission", sa.String(length=255), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role", "permission", name="uq_security_role_permissions_role_permission"),
    )
    op.create_index(op.f("ix_security_role_permissions_role"), "security_role_permissions", ["role"], unique=False)
    op.create_table(
        "security_secrets",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("secret_handle", sa.String(length=512), nullable=False),
        sa.Column("encrypted_payload", sa.LargeBinary(), nullable=False),
        sa.Column("algorithm", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "secret_handle", name="uq_security_secrets_tenant_handle"),
    )
    op.create_index(op.f("ix_security_secrets_secret_handle"), "security_secrets", ["secret_handle"], unique=False)
    op.create_index(op.f("ix_security_secrets_tenant_id"), "security_secrets", ["tenant_id"], unique=False)
    op.create_table(
        "workflow_definitions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("trigger_type", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.String(length=32), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("steps_json", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", "version", name="uq_workflow_definition_tenant_id_version"),
    )
    op.create_index(op.f("ix_workflow_definitions_tenant_id"), "workflow_definitions", ["tenant_id"], unique=False)
    op.create_table(
        "approval_decisions",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("approver_id", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("signature_hex", sa.String(length=256), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["request_id"], ["approval_requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id", name="uq_approval_decisions_request_id"),
    )
    op.create_index(op.f("ix_approval_decisions_request_id"), "approval_decisions", ["request_id"], unique=True)
    op.create_index(op.f("ix_approval_decisions_tenant_id"), "approval_decisions", ["tenant_id"], unique=False)
    op.create_table(
        "document_versions",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("parent_version_id", sa.String(length=36), nullable=True),
        sa.Column("version_number", sa.String(length=32), nullable=False),
        sa.Column("lifecycle_state", sa.String(length=32), nullable=False),
        sa.Column("is_immutable", sa.Boolean(), nullable=False),
        sa.Column("author_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("bucket_name", sa.String(length=128), nullable=True),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256_hash", sa.String(length=64), nullable=True),
        sa.Column("security_classification", sa.String(length=32), nullable=False),
        sa.Column("security_labels_json", sa.Text(), nullable=True),
        sa.Column("security_owner_id", sa.String(length=64), nullable=True),
        sa.Column("lineage_path_json", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "document_id", "version_number", name="uq_tenant_doc_ver_num"),
    )
    op.create_index(op.f("ix_document_versions_document_id"), "document_versions", ["document_id"], unique=False)
    op.create_index(
        op.f("ix_document_versions_lifecycle_state"), "document_versions", ["lifecycle_state"], unique=False
    )
    op.create_index(
        op.f("ix_document_versions_parent_version_id"), "document_versions", ["parent_version_id"], unique=False
    )
    op.create_index(op.f("ix_document_versions_sha256_hash"), "document_versions", ["sha256_hash"], unique=False)
    op.create_index(op.f("ix_document_versions_tenant_id"), "document_versions", ["tenant_id"], unique=False)
    op.create_table(
        "workflow_instances",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("definition_id", sa.String(length=64), nullable=False),
        sa.Column("definition_version", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("current_step_index", sa.Integer(), nullable=False),
        sa.Column("current_step_id", sa.String(length=64), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("context_json", sa.Text(), nullable=False),
        sa.Column("compensation_stack_json", sa.Text(), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["definition_id"], ["workflow_definitions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workflow_instances_definition_id"), "workflow_instances", ["definition_id"], unique=False)
    op.create_index(op.f("ix_workflow_instances_state"), "workflow_instances", ["state"], unique=False)
    op.create_index(op.f("ix_workflow_instances_tenant_id"), "workflow_instances", ["tenant_id"], unique=False)
    op.create_index("ix_workflow_instances_tenant_state", "workflow_instances", ["tenant_id", "state"], unique=False)
    op.create_table(
        "workflow_schedules",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("definition_id", sa.String(length=64), nullable=False),
        sa.Column("schedule_type", sa.String(length=32), nullable=False),
        sa.Column("cron_expression", sa.String(length=64), nullable=True),
        sa.Column("interval_seconds", sa.Integer(), nullable=True),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_instance_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("initial_context_json", sa.Text(), nullable=False),
        sa.Column("max_runs", sa.Integer(), nullable=True),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["definition_id"], ["workflow_definitions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_workflow_schedules_tenant_name"),
    )
    op.create_index(op.f("ix_workflow_schedules_definition_id"), "workflow_schedules", ["definition_id"], unique=False)
    op.create_index("ix_workflow_schedules_due", "workflow_schedules", ["status", "next_run_at"], unique=False)
    op.create_index(op.f("ix_workflow_schedules_next_run_at"), "workflow_schedules", ["next_run_at"], unique=False)
    op.create_index(op.f("ix_workflow_schedules_status"), "workflow_schedules", ["status"], unique=False)
    op.create_index(op.f("ix_workflow_schedules_tenant_id"), "workflow_schedules", ["tenant_id"], unique=False)
    op.create_index("ix_workflow_schedules_tenant_status", "workflow_schedules", ["tenant_id", "status"], unique=False)
    op.create_table(
        "workflow_step_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("instance_id", sa.String(length=36), nullable=False),
        sa.Column("step_id", sa.String(length=64), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("output_json", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["instance_id"], ["workflow_instances.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workflow_step_runs_instance_id"), "workflow_step_runs", ["instance_id"], unique=False)
    op.create_index("ix_workflow_step_runs_lookup", "workflow_step_runs", ["instance_id", "step_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_workflow_step_runs_lookup", table_name="workflow_step_runs")
    op.drop_index(op.f("ix_workflow_step_runs_instance_id"), table_name="workflow_step_runs")
    op.drop_table("workflow_step_runs")
    op.drop_index("ix_workflow_schedules_tenant_status", table_name="workflow_schedules")
    op.drop_index(op.f("ix_workflow_schedules_tenant_id"), table_name="workflow_schedules")
    op.drop_index(op.f("ix_workflow_schedules_status"), table_name="workflow_schedules")
    op.drop_index(op.f("ix_workflow_schedules_next_run_at"), table_name="workflow_schedules")
    op.drop_index("ix_workflow_schedules_due", table_name="workflow_schedules")
    op.drop_index(op.f("ix_workflow_schedules_definition_id"), table_name="workflow_schedules")
    op.drop_table("workflow_schedules")
    op.drop_index("ix_workflow_instances_tenant_state", table_name="workflow_instances")
    op.drop_index(op.f("ix_workflow_instances_tenant_id"), table_name="workflow_instances")
    op.drop_index(op.f("ix_workflow_instances_state"), table_name="workflow_instances")
    op.drop_index(op.f("ix_workflow_instances_definition_id"), table_name="workflow_instances")
    op.drop_table("workflow_instances")
    op.drop_index(op.f("ix_document_versions_tenant_id"), table_name="document_versions")
    op.drop_index(op.f("ix_document_versions_sha256_hash"), table_name="document_versions")
    op.drop_index(op.f("ix_document_versions_parent_version_id"), table_name="document_versions")
    op.drop_index(op.f("ix_document_versions_lifecycle_state"), table_name="document_versions")
    op.drop_index(op.f("ix_document_versions_document_id"), table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index(op.f("ix_approval_decisions_tenant_id"), table_name="approval_decisions")
    op.drop_index(op.f("ix_approval_decisions_request_id"), table_name="approval_decisions")
    op.drop_table("approval_decisions")
    op.drop_index(op.f("ix_workflow_definitions_tenant_id"), table_name="workflow_definitions")
    op.drop_table("workflow_definitions")
    op.drop_index(op.f("ix_security_secrets_tenant_id"), table_name="security_secrets")
    op.drop_index(op.f("ix_security_secrets_secret_handle"), table_name="security_secrets")
    op.drop_table("security_secrets")
    op.drop_index(op.f("ix_security_role_permissions_role"), table_name="security_role_permissions")
    op.drop_table("security_role_permissions")
    op.drop_index(op.f("ix_security_principals_tenant_id"), table_name="security_principals")
    op.drop_index(op.f("ix_security_principals_principal_id"), table_name="security_principals")
    op.drop_table("security_principals")
    op.drop_index(op.f("ix_security_audit_records_timestamp_utc"), table_name="security_audit_records")
    op.drop_index(op.f("ix_security_audit_records_tenant_id"), table_name="security_audit_records")
    op.drop_index(op.f("ix_security_audit_records_resource_id"), table_name="security_audit_records")
    op.drop_index(op.f("ix_security_audit_records_audit_id"), table_name="security_audit_records")
    op.drop_index(op.f("ix_security_audit_records_actor_id"), table_name="security_audit_records")
    op.drop_index(op.f("ix_security_audit_records_action"), table_name="security_audit_records")
    op.drop_table("security_audit_records")
    op.drop_index(op.f("ix_knowledge_records_tenant_id"), table_name="knowledge_records")
    op.drop_index(op.f("ix_knowledge_records_record_id"), table_name="knowledge_records")
    op.drop_table("knowledge_records")
    op.drop_index(op.f("ix_knowledge_packs_tenant_id"), table_name="knowledge_packs")
    op.drop_table("knowledge_packs")
    op.drop_index(op.f("ix_knowledge_annotations_tenant_id"), table_name="knowledge_annotations")
    op.drop_index(op.f("ix_knowledge_annotations_target_record_id"), table_name="knowledge_annotations")
    op.drop_index(op.f("ix_knowledge_annotations_insertion_sequence"), table_name="knowledge_annotations")
    op.drop_table("knowledge_annotations")
    op.drop_index(op.f("ix_idempotency_records_tenant_id"), table_name="idempotency_records")
    op.drop_index(op.f("ix_idempotency_records_state"), table_name="idempotency_records")
    op.drop_index(op.f("ix_idempotency_records_idempotency_key"), table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index(op.f("ix_finance_invoices_tenant_id"), table_name="finance_invoices")
    op.drop_table("finance_invoices")
    op.drop_index("ix_external_executions_tenant_status", table_name="external_executions")
    op.drop_index(op.f("ix_external_executions_tenant_id"), table_name="external_executions")
    op.drop_index(op.f("ix_external_executions_status"), table_name="external_executions")
    op.drop_index(op.f("ix_external_executions_idempotency_key"), table_name="external_executions")
    op.drop_table("external_executions")
    op.drop_index(op.f("ix_event_outbox_topic"), table_name="event_outbox")
    op.drop_index(op.f("ix_event_outbox_tenant_id"), table_name="event_outbox")
    op.drop_index(op.f("ix_event_outbox_status"), table_name="event_outbox")
    op.drop_table("event_outbox")
    op.drop_index(op.f("ix_documents_tenant_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_current_version_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_document_template_schemas_tenant_id"), table_name="document_template_schemas")
    op.drop_index(op.f("ix_document_template_schemas_template_id"), table_name="document_template_schemas")
    op.drop_index(op.f("ix_document_template_schemas_namespace"), table_name="document_template_schemas")
    op.drop_table("document_template_schemas")
    op.drop_index(op.f("ix_document_operation_profiles_tenant_id"), table_name="document_operation_profiles")
    op.drop_index(op.f("ix_document_operation_profiles_profile_id"), table_name="document_operation_profiles")
    op.drop_index(op.f("ix_document_operation_profiles_namespace"), table_name="document_operation_profiles")
    op.drop_index(op.f("ix_document_operation_profiles_business_operation"), table_name="document_operation_profiles")
    op.drop_table("document_operation_profiles")
    op.drop_index(op.f("ix_document_operation_history_version_id"), table_name="document_operation_history")
    op.drop_index(op.f("ix_document_operation_history_tenant_id"), table_name="document_operation_history")
    op.drop_index(op.f("ix_document_operation_history_request_id"), table_name="document_operation_history")
    op.drop_index(op.f("ix_document_operation_history_profile_id"), table_name="document_operation_history")
    op.drop_index(op.f("ix_document_operation_history_document_id"), table_name="document_operation_history")
    op.drop_table("document_operation_history")
    op.drop_index(op.f("ix_connector_profiles_tenant_id"), table_name="connector_profiles")
    op.drop_table("connector_profiles")
    op.drop_table("connector_action_history")
    op.drop_index("ix_approval_requests_tenant_state", table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_tenant_id"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_state"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_requester_principal_id"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_instance_id"), table_name="approval_requests")
    op.drop_index("ix_approval_requests_instance", table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_correlation_id"), table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index(op.f("ix_approval_delegations_tenant_id"), table_name="approval_delegations")
    op.drop_index("ix_approval_delegations_lookup", table_name="approval_delegations")
    op.drop_table("approval_delegations")
    op.drop_index(op.f("ix_ai_tenant_quotas_tenant_id"), table_name="ai_tenant_quotas")
    op.drop_table("ai_tenant_quotas")
    op.drop_index(op.f("ix_ai_governance_policies_tenant_id"), table_name="ai_governance_policies")
    op.drop_table("ai_governance_policies")
    op.drop_index("ix_ai_decision_tenant_created", table_name="ai_decision_records")
    op.drop_table("ai_decision_records")
    op.drop_index("ix_ai_conversation_turn_lookup", table_name="ai_conversation_turns")
    op.drop_table("ai_conversation_turns")
    op.drop_index("ix_ai_agent_task_tenant_status", table_name="ai_agent_tasks")
    op.drop_index("ix_ai_agent_task_lookup", table_name="ai_agent_tasks")
    op.drop_table("ai_agent_tasks")
    # ### end Alembic commands ###
